services:

  db:
    image: postgres:15
    expose:
      - "5432"
    env_file: .env
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ${CSV_PATH}:/data
      - ${EX02_PATH}:/scripts
    networks:
      - piscineds_network
    restart: always

  pgadmin:
    image: dpage/pgadmin4:8.12
    ports:
      - "8080:80"
    env_file: .env
    depends_on:
      - db
    networks:
      - piscineds_network
    restart: always

secrets:
  postgres_password:
    file: secrets/postgres_password
  postgres_user:
    file: secrets/postgres_user
  postgres_db:
    file: secrets/postgres_db

networks:
  piscineds_network:

volumes:
  pgdata:
    external: true
  data:
  scripts:
